services:
  - type: web
    name: mc-ph-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: mc-ph-app
          property: port
      - key: MONGODB_URI
        value: CHANGE_THIS_TO_YOUR_ATLAS_CONNECTION_STRING
